### ISSUE TITLE
SubmissionStatus (model): Misses State "Translate"

### ISSUE THREAD

**Issue by mmichaelis** [translations-com/globallink-connect-cloud-api-java#1]
The model class `org.gs4tr.gcc.restclient.model.SubmissionStatus` does not reflect the state `Translate` which a typical submission might hold for a considerable amount of time.

See also: GlobalLink QuickStart Documentation/State Flow

Note, that in addition to this the following states are not mentioned in the state flow diagram:

* `Awaiting Approval`
* `Awaiting Quote Approval`
* `In Progress` (I assume this is, what `Translate` is now)
* `Review`

Either the model class needs to be adapted accordingly, or the QuickStart documentation misses some states.

**Comment by masanzsa** [comment]
Hi @mmichaelis,

First of all thanks a lot for your feedback. I have been able to reproduce the issues you are mentioning, which are related to the model classes `SubmissionStatus` `TaskStatus` and `JobStatus`.

So far, the easiest way to overcome this would be by setting a raw text array for each of the statuses (please note the lists are not exactly the same):

*For Submissions*
```
//Pick one, several, or all statuses
String[] subStatuses = { "Pre-process", "Started", "Analyzed", "Approval", "Translate", "Review", "Completed", "Delivered" };
SubmissionsListRequest submissionsListRequest = new SubmissionsListRequest();
submissionsListRequest.setSubmissionStatuses(subStatuses);
SubmissionsResponseData submissionResponseData = gcexchange.getSubmissionsList(submissionsListRequest);	
```

*For Jobs*
```
//Pick one, several or all statuses
String[] jobStatuses = { "Pre-process", "Started", "Analyzed", "Awaiting Approval", "Awaiting Quote Approval", "Translate", "Review", "Completed", "Delivered" };
JobListRequest jobListRequest = new JobListRequest();
jobListRequest.setJobStatuses(jobStatuses);
JobsResponseData jobList = gcexchange.getJobsList(jobListRequest);
```

*For Tasks*
```
//Pick one, several or all statuses
String[] taskStatuses = { "Processing", "Analyzed", "Translate", "Review", "Review-Completed", "Completed", "Delivered", "Rejected", "Cancelled" };
taskListRequest.setTaskStatuses(taskStatuses);
TasksResponseData tasksResponseData = gcexchange.getTasksList(taskListRequest);
```

Please note if no pageSize is defined, we default it to 10 items.
i.e.
`submissionsListRequest.setPageSize((long) 100);` or `jobListRequest.setPageSize((long) 100);` or `taskListRequest.setPageSize((long) 100);`

We will work on the next release 2.2.0_RC1 to fix the issues in the classes mentioned above. 

Please accept our apologies for the inconveniences caused. 

Thanks!

Mariano Sanz
