### ISSUE TITLE
What are the changes of the 3.0.0 release?

### ISSUE THREAD

**Issue by aprantl** [translations-com/globallink-connect-cloud-api-java#12]
Maven Central mentions that there is a 3.0.0 release. Please update this repository with the changes since the 2.2.1 release and provide a changelog so that API developers can migrate their code accordingly.

**Comment by SergeiTsybulko** [comment]
Changelog created for 3.0.0 release. Can be found here:
https://github.com/translations-com/globallink-connect-cloud-api-java/blob/master/CHANGELOG.md
