### ISSUE TITLE
Please revert: Changing Return type of GCExchange.confirmTaskCancellation

### ISSUE THREAD

**Issue by mmichaelis** [translations-com/globallink-connect-cloud-api-java#2]
https://github.com/translations-com/globallink-connect-cloud-api-java/blob/beeab99864d1a30fa482dd34db464f80d6c54540/src/main/java/org/gs4tr/gcc/restclient/GCExchange.java#L437

In a recent commit, the return type of `GCExchange.confirmTaskCancellation` got changed to `TasksConfirmCancellationResponse` rather than returning the embedded list of the response data. This breaks for all users of the 2.2.0 API for no gain:

There is no relevant information (at least in its current state) inside the response object. You still have to navigate to the list of `TaskCancelConfirmation` items.

What should have changed is the JavaDoc which just stated _is success_. Instead, if I get the implementation of `TasksConfirmCancellationResponseData` correctly, it returns the list of all failed task cancellation confirmations. So, the complete cancellation was successful, when this list is empty &mdash; at least this is my assumption from the JSON property name `fail_tasks`.

In addition to this it would be helpful to rename `TaskCancelConfirmation` to `TaskCancelConfirmationFailure` which would tell the API user, what this list is about without the need to read JavaDoc.

**Comment by SergeiTsybulko** [comment]
Thank you. Issue is resolved now:
1. TaskCancelConfirmation renamed to TaskConfirmCancellationFailure
2. GCExchange.confirmTaskCancellation will now return List<TaskConfirmCancellationFailure>
3. JavaDoc updated
