### ISSUE TITLE
Minor: PageableRequest and corresponding PageableResponseData: Different type for page (count)

### ISSUE THREAD

**Issue by mmichaelis** [translations-com/globallink-connect-cloud-api-java#4]
While the `PageableRequest` uses `Long` for page number for example:

https://github.com/translations-com/globallink-connect-cloud-api-java/blob/5f5e3ed4ef6c2b2aa6eca60afab9eadf3cc36f05/src/main/java/org/gs4tr/gcc/restclient/request/PageableRequest.java#L11

The corresponding `PageableResponseData` returns `Integer` for the very same values:

https://github.com/translations-com/globallink-connect-cloud-api-java/blob/5f5e3ed4ef6c2b2aa6eca60afab9eadf3cc36f05/src/main/java/org/gs4tr/gcc/restclient/dto/PageableResponseData.java#L9

Would be nice, if you would streamline the types.

**Comment by SergeiTsybulko** [comment]
PageableResponseData fields (currentPageNumber, totalRecordsCount, totalResultPagesCount) now will have type Long
